export * from "./Welcome";
export * from "./Home";
export * from "./Fact";
export * from "./BridgeConstruction";
export * from "./TurnOffWater";
export * from "./BeautifulPlace";
export * from "./FreeWiFi";
export * from "./Offline";
export * from "./Map";
