export enum PANEL_ROUTES {
  WELCOME = "WELCOME",
  HOME = "HOME",
  FACT = "FACT",
  BRIDGE_CONSTRUCTION = "BRIDGE_CONSTRUCTION",
  TURN_OFF_WATER = "TURN_OFF_WATER",
  NOTIFICATION = "NOTIFICATION",
  BEAUTIFUL_PLACE = "BEAUTIFUL_PLACE",
  FREE_WIFI = "FREE_WIFI",
}
